name: 'CI'

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  tests:    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            lisp: sbcl-bin
          - os: macos-latest
            lisp: sbcl-bin
          - os: windows-latest
            lisp: sbcl-bin
          
    env:
      LISP: ${{ matrix.lisp }}
      OS: ${{ matrix.os }}
      QUICKLISP_DIST: ${{ matrix.quicklisp-dist }}

    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v2
        with:
          asdf-system: cl-info
          qlfile-template: |
            {% ifequal quicklisp_dist "ultralisp" %}
            dist ultralisp http://dist.ultralisp.org
            {% endifequal %}
      - name: test with ${{ matrix.lisp }} on ${{ matrix.os }}
      - run: sbcl --non-interactive --eval '(load "tests/main.lisp")'

