on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SBCL
        uses: cheeze2000/setup-sbcl@v1
        with:
          version: 2.2.8
      - name: Verify installation
        run: sbcl --non-interactive --eval '(progn (load "tests/package.lisp") (load "tests/main"))'
